V next
WASdev/ci.docker pull request #537
Opened 2023-08-21 20:51 UTC by wraschke

2023-08-21 21:11 UTC, leochr commented on ga/23.0.0.8/full/Dockerfile.ubi.openjdk11
> +ARG PARENT_IMAGE=icr.io/appcafe/websphere-liberty:kernel-java11-openj9-ubi
This should be 
```
ARG PARENT_IMAGE=icr.io/appcafe/websphere-liberty:23.0.0.8-kernel-java11-openj9-ubi
```

Looks good otherwise

2023-08-22 02:08 UTC, mbroz2 requested changes

2023-08-22 02:08 UTC, mbroz2 commented on ga/23.0.0.8/full/Dockerfile.ubi.openjdk11
> +ARG PARENT_IMAGE=icr.io/appcafe/websphere-liberty:kernel-java11-openj9-ubi
```suggestion
ARG PARENT_IMAGE=icr.io/appcafe/websphere-liberty:23.0.0.8-kernel-java11-openj9-ubi
```

2023-08-22 02:35 UTC, mbroz2 approved these changes

2023-08-22 02:37 UTC, wraschke commented
Thanks, Leo and Michal, for the spot. Line 15 of `ga/23.0.0.8/full/Dockerfile.ubi.openjdk11` should be fixed now with 23.0.0.8 in name.

2023-08-23 02:25 UTC, merged